import java.io.File

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.4.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // JavaFX dependencies with platform classifier
    val javafxVersion = "21.0.1"
    implementation("org.openjfx:javafx-controls:$javafxVersion:linux")
    implementation("org.openjfx:javafx-graphics:$javafxVersion:linux")
    implementation("org.openjfx:javafx-fxml:$javafxVersion:linux")
    implementation("org.openjfx:javafx-base:$javafxVersion:linux")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    // The class is CannonSimulation with companion object main
    mainClass = "org.example.CannonSimulation"
}

tasks.named<JavaExec>("run") {
    doFirst {
        val classpath = configurations.runtimeClasspath.get()
        val javafxJars = classpath.filter { (it as File).name.startsWith("javafx-") && (it as File).name.endsWith("-linux.jar") }
        val modulePath = javafxJars.joinToString(File.pathSeparator)
        if (modulePath.isNotEmpty()) {
            jvmArgs("--module-path", modulePath)
            jvmArgs("--add-modules", "javafx.controls,javafx.graphics,javafx.fxml,javafx.base")
        }
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}